environment:
  nodejs_version: "20"

image: Ubuntu2204
stack: node 20

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm test  # скрипт тестирования
